# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.0.1  # Use the latest tag for the pre-commit-hooks repository
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: git@github.com:pycqa/flake8.git
    rev: 3.9.2  # Use the latest stable version of flake8
    hooks:
    -   id: flake8
        args: [--max-line-length=88]  # Example argument to set line length

-   repo: git@github.com:pre-commit/mirrors-yamllint.git
    rev: v1.26.3  # Use the latest tag for the mirrors-yamllint repository
    hooks:
    -   id: yamllint

